### PR TITLE
Drop Python 3.9 from workflows.

### PR DESCRIPTION
**Pull request by bdice**
See https://github.com/rapidsai/build-planning/issues/88.

### CODE REVIEW

**Comment by bdice** [comment]
@jameslamb I went ahead and opened this because we need to drop Python 3.9 from our workflows in order to update our Dask pinning.

xref: https://github.com/rapidsai/build-planning/issues/88#issuecomment-2284805564

**Comment by bdice** [comment]
1. Here is a test PR in cudf to ensure that this matrix is usable: https://github.com/rapidsai/cudf/pull/16539
2. Let's merge https://github.com/rapidsai/cudf/pull/16540 before we merge this PR to avoid disruption in tests. There are no other instances of this in RAPIDS ([search link](https://github.com/search?q=org%3Arapidsai%20%2Fmatrix_filter.*3.9%2F&type=code)), just those two in cuDF.

**Review by KyleFromNVIDIA — APPROVED** [review]

**Review by jameslamb — APPROVED** [review]
Yes totally, I support it! Won't hurt to have a bit denser coverage of Python 3.10 in the interim, maybe it'll help catch something.

And I've approved https://github.com/rapidsai/cudf/pull/16540, thanks for thinking of that.

**Review by jakirkham — APPROVED** [review]

**Review by raydouglass — APPROVED** [review]

**Comment by jakirkham** [comment]
AFAIK the branch `drop-python-3.9` is unused in any workflow. So will go ahead and delete it. If I've missed something, it is easy to restore that branch

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
